# permissions for end users to view notificationconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: notificationconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gke-update-notification
    app.kubernetes.io/part-of: gke-update-notification
    app.kubernetes.io/managed-by: kustomize
  name: notificationconfig-viewer-role
rules:
- apiGroups:
  - notification.controller.renault.com
  resources:
  - notificationconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - notification.controller.renault.com
  resources:
  - notificationconfigs/status
  verbs:
  - get
