---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - notification.controller.renault.com
  resources:
  - notificationconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notification.controller.renault.com
  resources:
  - notificationconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - notification.controller.renault.com
  resources:
  - notificationconfigs/status
  verbs:
  - get
  - patch
  - update
