apiVersion: notification.controller.renault.com/v1alpha1
kind: NotificationConfig
metadata:
  labels:
    app.kubernetes.io/name: gke-update-notification
    app.kubernetes.io/managed-by: kustomize
  name: notificationconfig-sample
spec:
  # TODO(user): Add fields here
